# Generated by Django 6.0.3 on 2026-03-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postsToday', models.IntegerField(default=0)),
                ('totalPosts', models.IntegerField(default=0)),
                ('subscribersGained', models.IntegerField(default=0)),
                ('aiTokensUsed', models.IntegerField(default=0)),
                ('lastPostAt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='channels.channel')),
            ],
        ),
    ]
