# Generated by Django 6.0.3 on 2026-03-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_aimodel_channel_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='owner',
        ),
    ]
