# Generated by Django 6.0.3 on 2026-03-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_alter_cronjob_topic_postlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='telegram_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='channel',
            name='aiModel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
