# Generated by Django 6.0.3 on 2026-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channel_telegram_chat_id_channel_telegram_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('openai', 'OpenAI'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
