# Generated by Django 6.0.3 on 2026-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_aimodel_model_aimodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlog',
            name='media',
            field=models.TextField(blank=True, default=''),
        ),
    ]
