# Generated by Django 6.0.3 on 2026-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_postlog_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='lastRunAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
