# Generated by Django 6.0.3 on 2026-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_cronjob_lastrunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='with_images',
            field=models.BooleanField(default=False),
        ),
    ]
