# Generated by Django 6.0.3 on 2026-03-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_cronjob_with_images'),
        ('posts', '0002_post_error_alter_post_status_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('runs_total', models.IntegerField(default=0)),
                ('runs_success', models.IntegerField(default=0)),
                ('runs_failed', models.IntegerField(default=0)),
                ('posts_published', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('duration_total_ms', models.BigIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='channels.channel')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'date'], name='channels_ch_channel_8dad9d_idx'), models.Index(fields=['date'], name='channels_ch_date_80c8bc_idx')],
                'unique_together': {('channel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CronJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(blank=True, default='', max_length=20)),
                ('ai_model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_runs', to='channels.channel')),
                ('cron_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='channels.cronjob')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-started_at'], name='channels_cr_channel_3c6108_idx'), models.Index(fields=['cron_job', '-started_at'], name='channels_cr_cron_jo_72fc31_idx'), models.Index(fields=['status', '-started_at'], name='channels_cr_status_5d7c5c_idx')],
            },
        ),
    ]
