# Generated by Django 6.0.3 on 2026-03-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0011_cronjob_with_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('text_plain', models.TextField(blank=True, default='')),
                ('text_html', models.TextField(blank=True, default='')),
                ('media', models.TextField(blank=True, default='')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channels.channel')),
                ('cron_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='channels.cronjob')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-id'], name='posts_post_channel_a3828f_idx')],
            },
        ),
    ]
